### ISSUE TITLE
Support for keyword arguments

### ISSUE THREAD

**Issue by njatkinson** [ceelian/callme#36]
It would be nice if I were able to use keyword arguments in calls from the proxy to the server. Currently calls only support positional arguments.

It looks like it would be fairly straightforward to add a func_keywords attribute to the RpcRequest object in protocol.py, capture them when Proxy creates the request object (I can't seem to find relevant section of code), and unpack them together with positional arguments in line 143 of server.py as so:

`result = self._func_dict[request.func_name](*request.func_args, **request.func_kw_args)`

It's crunch time for me at work, so I don't have a lot of time to spend on this at the moment. If nobody has time to work on this, I can take a look again in a month or so and send a pull request with the feature in place.

**Comment by skudriashev** [comment]
@njatkinson, thanks for the comment. I'll take a look into this once I have time. How critical is this for you?

**Comment by njatkinson** [comment]
Thanks for the follow-up, @skudriashev.

I'll be deploying some code this week that uses callme. I've done a workaround for keyword arguments and don't want to change code this close to production. So, this isn't critical for me.

I like callme, and it would be nice to not have to workaround keyword arguments in the future, but I don't need it right away. I should have some time in about two weeks and can work on it then if you haven't had a chance yet.

**Comment by skudriashev** [comment]
@njatkinson, fixed. Thanks!
